### ISSUE TITLE
HM Bell für AskSinPP Projektgalerie

### ISSUE THREAD

**Issue by paso42** [AskSinPP/asksinpp-web#101]
Hallo Psi, 
ich habe die Dokumente zur Klingelsteuerung/-überwachung im Git soweit vorbereitet. Habe allerdings das Issue vergessen. Bitte einmal bescheid geben, sollte etwas fehlen.

https://github.com/paso42/HM-Bell

Viele Grüße

**Comment by psi-4ward** [comment]
Uuups sorry. Deine Mail ist wohl iwo hinten runter gefallen. Hab das Projekt aufgenommen.
