### ISSUE TITLE
Schellenberg Rollladen Gurtwickler mit AskSinPP steuern

### ISSUE THREAD

**Issue by kmbach** [AskSinPP/asksinpp-web#115]
Hallo,
ich würde gern meine Rollladengurtwickler von Schellenberg mittels AskSinPP steuern. Im Moment steuere ich zwei schon über einen HM-LC-Sw4-PCB. Das gefällt mir aber schon lange nicht mehr, weil ich im Gerät die Behanghöhe nicht vorgeben kann und auch nicht das Betätigen der Tasten in der Homematic mitbekomme. Deshalb habe ich zwei weitere Schellenberger mittels ESP32 und MQTT an die Homematic gebracht. Hier bin ich natürlich völlig offen und kann alle Anforderungen umsetzen. Nachteil ist der hohe Hardwareaufwand, da, auf Grund der hohen Stromaufnahme des ESP32 eine zusätzlich Stromversorgung (AC/DC) in das Gehäuse muß. Und genau diese bekomme ich in die über HM-LC-Sw4-PCB gesteuerten Gurtwickler nicht rein. Nun bin ich auf AskSinPP gestoßen und habe auch bereits einen HB-UNI-Sen-SUMMY-BEACON V2 mit AskSinAnalyzer-Sniffer realisiert.
Für die Steuerung schwebt mir nun ein AskSinPP device vor, welches über 2x Eingang, 2x Ausgang verfügt und in das ich einen Wert für die Behanghöhe schreiben kann. Jede Taste des Gurtwicklers (up,down) bekommt parallel einen Ein- und Ausgang (Ausgang über 3,3V Reedrelais). Die Schellenberger verfügen über eine Rolle mit Impulsgeber. Deren Impulse möchte ich in dem Sketch abgreifen und zur Steuerung der Behanghöhe nutzen (mache ich mit dem ESP32 so). Über die Tasten möchte ich bei 'langem Druck' dann eine Gruppe steuern - der kann dann ein Homematic Programm triggen. 
Also für die einfache Steuerung (up,down, Gruppe) würde ein HB-UNI-SenAct-4-4-RC genügen. Damit habe ich aber noch keine Lösung für die Entgegennahme einer Behanghöhe. Ja, Behanghöhe steuere ich jetzt auch über die Zeit.
Als Grundlage für das Vorhaben würde sich im ersten Moment ein Device zur Rollladensteuerung anbieten. Damit wäre auch das Problem der Behanghöhe erledigt. Fehlen allerdings die benötigten Eingänge.

Ich sehe zwei mögliche Wege:
1. Das HB-UNI-SenAct-4-4-RC modifizieren indem dieses auf 2-2 verringert wird und eine Möglichkeit zur Übernahme/Auslesen eines Wertes für die Behanghöhe erhält.
2. Ein Rollladendevice um zwei Eingänge erweitern.

Variante 2 ist vermutlich die elegantere Lösung weil dann auch die Darstellung im GUI paßt. Dazu brauchts dann aber vermutlich auch eine Erweiterung des Addon's "JP HB Devices".

Leider fehlt mir noch völlig der Überblick darüber, was in der AskSinPP Library passiert, welche Aufrufe man diesbezüglich im Sketch tätigen kann/muß und dem Zusammenhang zur grafischen Darstellung des divices in der homematic GUI. 

Hat jemand eine Idee oder kann mich hier Unterstützen?  

Gruß kmbach

**Comment by psi-4ward** [comment]
Hi, ich denke im homematic forum ist diese Frage besser aufgehoben.

**Comment by kmbach** [comment]
Okay

**Comment by kmbach** [comment]
Naja, habe ich hier vielleicht zu schnell aufgegeben. Im Homematic- Forum finde ich jedenfalls nichts was in die Richtung meines Vorhabens zeigt. Daher glaube ich auch, dass ich hier besser aufgehoben wäre. Ich versuche es, deshalb hier, einfach noch einmal.
