### ISSUE TITLE
Phasenanschnittdimmer HM-LC-Dim1L-CV

### ISSUE THREAD

**Issue by mankut80** [AskSinPP/asksinpp-web#128]
Hallo, 
in der Hoffnung, dass in diesem Repo noch Leben herrscht, habe ich einen HM-LC-Dim1L-CV Phasenanschnittdimmer zusammengebastelt. Darf dieser seinen Weg in die AsksinPP-Projektbibliothek finden?
Leider habe ich das mit den Pull-Requests nicht kapiert, sonst hätte ich gerne diesen Weg genutzt.

Das Projekt liegt hier: 
https://maschmid.next-cloud.org/index.php/s/7gZ2EqyjfMeqoK9
Alternativ als Zip: [HM-LC-Dim1L-CV.zip](https://github.com/AskSinPP/asksinpp-web/files/14910530/HM-LC-Dim1L-CV.zip)

Einen kleinen Haken gibt es allerdings:
ohne einer Änderung in PWM.h und phasecut.cpp des Masterbranches wird bei einer Dim-Einstellung von "0" der Ausgang auf  Dauer-An gestellt (zumindest unter FHEM zeigt er dieses Verhalten, mit einer CCU vermutlich auch). Die Änderung steht im Markdownfile des Projektordners. Ich bin mir nicht sicher, ob das ein wirklicher Bug ist oder ich selbst einen Fehler gemacht habe (was tendenziell eher der Fall ist).

Grüße, Markus

**Comment by psi-4ward** [comment]
Hi,
ich füge das Projekt gerne hinzu allerdings wäre es als Github-Repository besser aufgehoben als in deiner privaten Nextcloud oder?

Grüße

**Comment by mankut80** [comment]
wohl wahr :-). 
Das Repo ist hier: https://github.com/mankut80/AskSinPP_HM-LC-Dim1L-CV
Vielen Dank :)

**Comment by psi-4ward** [comment]
b2f6284490ed912e9d074cc335b2d755497d8f8a

**Comment by mankut80** [comment]
perfekt, Danke
